let mock = [
  {
    id: 1,
    name: "Toy Story 4",
    rating: "PG",
    genre: "Animation / Comedy",
    year: 2019,
    image: "toystory.jpg",
  },
  {
    id: 2,
    name: "Coco",
    rating: "PG",
    genre: "Animation / Comedy",
    year: 2017,
    image: "coco.jpg",
  },
  {
    id: 3,
    name: "Black Panther",
    rating: "PG-13",
    genre: "Adventure / Action",
    year: 2018,
    image: "blackpanther.jpg",
  },
  {
    id: 4,
    name: "La La Land",
    rating: "PG-13",
    genre: "Romance / Comedy",
    year: 2016,
    image: "lalaland.jpg",
  },
  {
    id: 5,
    name: "GroundHog Day",
    rating: "PG-13",
    genre: "Romance",
    year: 1993,
    image: "ghog.jpg",
  },
  {
    id: 6,
    name: "The Avengers",
    rating: "PG-13",
    genre: "Science-Fiction / Adventure",
    year: 2019,
    image: "endgame.jpg",
  },
  {
    id: 7,
    name: "Wonder Woman",
    rating: "PG-13",
    genre: "Fantasy / Action",
    year: 2017,
    image: "ww.jpg",
  },
  {
    id: 8,
    name: "Dark Knight",
    rating: "PG-13",
    genre: "Adventure / Action",
    year: 2008,
    image: "darkknight.jpg",
  },
  {
    id: 9,
    name: "Wonderful Life",
    rating: "PG",
    genre: "Comedy / Other",
    year: 1946,
    image: "wonderfullife.jpg",
  },
  {
    id: 10,
    name: "Star Wars V",
    rating: "PG",
    genre: "Science-Fiction / Fantasy",
    year: 1980,
    image: "starwars.jpg",
  },
];

export default mock;
